# Railway configuration for Docker deployment
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"

# Database variables - set these manually in Railway dashboard
# DATABASE_URL = mysql://root:[password]@[host]:3306/[database]
# DB_HOST = [mysql_host]
# DB_PORT = "3306"
# DB_USERNAME = "root"
# DB_PASSWORD = [mysql_password]
# DB_NAME = [database_name]