# Railway Configuration for Backend Only - AGGRESSIVE DOCKER FORCE
# This ensures Railway builds only the backend using Docker, ignoring everything else

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

# Force Docker build and completely ignore Nixpacks
[build.docker]
dockerfile = "Dockerfile.railway"
context = "."
ignore = [".nixpacks", "../package.json", "../package-lock.json"]

# Explicitly set the build context to backend only
[build.context]
path = "."

# Exclude any parent directories or root files
exclude = [
    "../package.json",
    "../package-lock.json", 
    "../node_modules",
    "../frontend",
    "../.git",
    ".nixpacks",
    "../.nixpacks"
]

# Force Railway to use this directory only
[project]
root = "."

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_PREFER_OFFLINE = "true"

# Database configuration - these will be set in Railway dashboard
# DB_HOST = "your-railway-mysql-host"
# DB_PORT = "3306"
# DB_USERNAME = "your-railway-mysql-username"
# DB_PASSWORD = "your-railway-mysql-password"
# DB_NAME = "your-railway-mysql-database"

# Frontend URL for CORS
FRONTEND_URL = "https://your-frontend-domain.railway.app"

# File upload configuration
MAX_FILE_SIZE = "10485760"
UPLOAD_PATH = "./uploads"

# OCR Configuration
TESSERACT_LANG = "eng"
TESSERACT_CONFIG = "--oem 3 --psm 6"

